# Generated by Django 2.0.2 on 2018-02-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fund_name',
            new_name='fund_info',
        ),
    ]
